import { Directive } from "../Directive";
import { ByteArray } from "../ByteArray"

/**
 * Executes the given `.addr` command and returns a byte array of zeros
 * this byte array should be replace by the label address
 * representation generated by the command.
 * @param {Directive} command The command to execute.
 * @return {ByteArray} The byte array generated by the command.
 */
export function addr(command: Directive): ByteArray {
    const { line, params } = command
    if (params.length === 0) {
        return null
    }
    const bytes = [0, 0]
    return new ByteArray({ bytes, line })
}